Vagrant.configure("2") do |config|

  config.vm.define "ubuntu-1604" do |machine|
    machine.vm.box = "ubuntu/xenial64"    
	machine.vm.network "private_network", ip: "192.168.150.10"
  end
  
  config.vm.synced_folder "../data", "/vagrant_data"
  config.vm.synced_folder "../../ansible", "/ansible"
  
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = true
    vb.cpus = 2
    # Customize the amount of memory on the VM:
    vb.memory = "2048"
  end
  
  config.vm.provision "ansible_local" do |ansible|
    ansible.provisioning_path = "/ansible"
    ansible.playbook = "sample-env-ops-provision.yml"
    ansible.galaxy_role_file = "requirements.yml"
    ansible.galaxy_roles_path = "/etc/ansible/roles"
    ansible.galaxy_command = "sudo ansible-galaxy install --role-file=%{role_file} --roles-path=%{roles_path} --force --ignore-certs"    
  end
end