---
maven_artifact_repository_url:
maven_artifact_group_id: 
maven_artifact_id: 
maven_artifact_version: 
maven_artifact_extension: 
maven_artifact_classifier: 
maven_artifact_instance_folder: 
maven_artifact_symlink:
