---
# https://hub.docker.com/_/postgres/
- name: create a directory if it doesn't exist
  file:
    path: /solution/docker-postgres/postgresql/data/pgdata
    state: directory
    recurse: yes

- name: run docker postgres
  docker_container:
    name: docker-postgres
    image: postgres:11
    published_ports: 5432:5432
    restart_policy: unless-stopped
    state: started
    volumes:
      - /solution/docker-postgres/postgresql/data/pgdata:/var/lib/postgresql/data/pgdata
    env: PGDATA=/var/lib/postgresql/data/pgdata, POSTGRES_PASSWORD=password