---
- name: download nvidia docker
  get_url: 
    url: https://github.com/NVIDIA/nvidia-docker/releases/download/v1.0.1/nvidia-docker_1.0.1-1_amd64.deb
    dest: "/tmp/nvidia-docker_1.0.1-1_amd64.deb"

- name: install nvidia docker
  apt: 
    deb: "/tmp/nvidia-docker_1.0.1-1_amd64.deb"